version: '3'

services:
  djangoapp:
    build: .
    restart: always
    environment:
      - DJANGO_ENVIRONMENT=STG_DOCKER
    ports:
      - 8000:8000
    volumes:
      - .:/opt/services/web_app/src
    command: ["gunicorn", "--workers", "3", "--timeout", "120", "--chdir", "web_app", "--bind", ":8000", "web_app.wsgi:application"]
    container_name: web_stg_app
    expose:
        - "8000"
